$pdf_mode = 1;
$pdf_previewer = 'okular %O %S';


add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
push @generated_exts, 'gls',  'gls', 'glg';


add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');
push @generated_exts, 'acn',  'acr', 'alg';

$clean_ext .= ' %R.ist %R.xdy';


sub run_makeglossaries {
    if ( $silent ) {
      system "makeglossaries -q '$_[0]'";
    }
    else {
      system "makeglossaries '$_[0]'";
    }
}
